### ISSUE TITLE
Memegen Support

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/DrinkWaterBot#11]
Would the maintainers be open to allowing a command, say
```
meme
```
in response to which DrinkWaterBot would respond with a link to a meme?

Future scope could include some content injection or meme templates, such as 
```
meme <template> <text of meme>
```
which would return a link to a meme generated through the [memegen API](https://api.memegen.link/).

I would like to work on this. Thank you :D

**Comment by srujandeshpande** [comment]
yes

**Comment by anirudhRowjee** [comment]
on it
