### ISSUE TITLE
Add a slash command for memegen

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/DrinkWaterBot#149]
### What do you want to see?

@anirudhRowjee has added some amazing new functionality with memegen support (#148). It would be great to have this as a slash command as well!
You can refer to [`src/commands/meme.js`](https://github.com/acmpesuecc/DrinkWaterBot/blob/master/src/commands/meme.js) for the original code. The `src/slashCommands/` directory contains code for other commands that you can refer to for slash commands.

**Comment by Gurvir-Sandhar** [comment]
I can work on this!
