### ISSUE TITLE
The .gitignore is too big

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/DrinkWaterBot#41]
There's no point in having a big gitignore that handles files created from a bunch of frameworks we don't even use. It's not about memory or anything, it's about the principle. Also the .gitignore needs some better commenting as well while we're at it

**Comment by Bloodslayer7** [comment]
can I get assigned to this issue

**Comment by Prajwal-creator007** [comment]
I would like to be assigned to this issue

**Comment by ArnavKumar7** [comment]
yes, you can work on it, I have assigned it to both of you
