### ISSUE TITLE
Add emojis to `water space people`

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/DrinkWaterBot#86]
Emojis make messages fun! Add some emojis in the output for the `water space people` command.

(Not too many though! Just enough to be colorful ;)

**Comment by arrowarchit** [comment]
Hey, can you please assign this task to me?

**Comment by karunakc** [comment]
> I can take this?

Sure, all the best!

**Comment by ArnavKumar7** [comment]
yes, sure both of you can work on the issue :)
