### ISSUE TITLE
Update required node.js version in CONTRIBUTING.md

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/DrinkWaterBot#87]
https://github.com/acmpesuecc/DrinkWaterBot/blob/a8cf8e61661967de0118e2a3f33ab881b9974d9a/CONTRIBUTING.md?plain=1#L7

The version of node.js specified in the contributing docs is for the current version of the bot. When #78 is merged, the minimum version of node.js required will be **16.6.0**. Earlier versions will _not_ work.

This has to be updated in the docs. 
This PR will be merge after #78 is merged.

**Comment by arrowarchit** [comment]
@srujandeshpande Hi, please review my PR for this issue. Thanks

**Comment by ArnavKumar7** [comment]
yeah, sure , i will assign the issue to you , you can go ahead and work, please take care of it from next time, thanks for the eagerness to work on the issue :)

**Comment by JoyenBenitto** [comment]
hey I want to work in this

**Comment by anirudhlakhotia** [comment]
I'd like to try this
